[PORT] Port stock_split_picking to 10.0
avoinsystems/stock-logistics-warehouse pull request #1
Opened 2017-03-03 12:35 UTC by aisopuro

Make some changes to the basic workflow, as the picking workflow was
changed in 9.0. There is no longer a separate wizard for processing
the packing operations, rather they are visible on the picking
form. As such, we emulate the normal backorder creation as
closely as possible, while not actually creating a backorder.

2017-03-03 12:58 UTC, mlaitinen requested changes
Nothing big. Please answer my few questions.

2017-03-03 12:58 UTC, mlaitinen commented on stock_split_picking/model/stock.py
> +                raise UserError(_("You can only split pickings "))
Missing the rest of the error message

2017-03-03 12:58 UTC, mlaitinen commented on stock_split_picking/model/stock.py
> +        # These are not backorders we've created, only splits from the original picking
What's the difference? Why can't it be considered a backorder?

2017-03-03 13:03 UTC, aisopuro commented on stock_split_picking/model/stock.py
> +        # These are not backorders we've created, only splits from the original picking
If we keep it as a backorder, we will be unable to split the picking a second time, as the core logic assumed `backorder_id` to practically be a `One2one` field.

2017-03-03 13:17 UTC, mlaitinen commented on stock_split_picking/model/stock.py
> +        # These are not backorders we've created, only splits from the original picking
Allright. Of course because the core logic assumes the first part is `done` after the backorder has been created.

2017-03-06 11:26 UTC, mlaitinen approved these changes

2017-03-06 11:51 UTC, mtnarjan approved these changes

2017-03-07 12:28 UTC, merged